settings:
  title: 'My Site Status Page'
  url: 'https://cf-workers-status-page-production.imydl.workers.dev/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: imydl-com # unique identifier
    name: imydl-com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://www.imydl.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: imydl-tech
    name: imydl.tech
    description: 'Built for anything connected to the Internet.'
    url: 'https://www.imydl.tech/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: Nav
    name: Tech-Nav
    url: 'https://nav.imydl.tech/'
    method: GET
    expectStatus: 200

  - id: Nyjwsw # unique identifier
    name: Nyjwsw.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://www.nyjwsw.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
  - id: Nokinsgolfcart # unique identifier
    name: Nokinsgolfcart.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://nokinsgolfcart.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
  - id: love-forex # unique identifier
    name: love-forex.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://www.love-forex.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: swisschooser # unique identifier
    name: swisschooser.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://swisschooser.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: e-investingguide # unique identifier
    name: e-investingguide.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://www.e-investingguide.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: 51sytx # unique identifier
    name: 51sytx.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://www.51sytx.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: Gxtesjy.com # unique identifier
    name: 寿菌园官网
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://www.gxtesjy.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: Kvxr # unique identifier
    name: kvxr.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://www.kvxr.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: 499h # unique identifier
    name: 499h.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://499h.com' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
