settings:
  title: 'My Site Status Page'
  url: 'https://status.imydl.tech' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: imydl # unique identifier
    name: imydl.com
    description: '草根博客' # default=empty
    url: 'https://www.imydl.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: tech
    name: imydl.tech
    description: '运维学习笔记'
    url: 'https://www.imydl.tech/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: Nav
    name: Tech-Nav
    description: '私人导航'
    url: 'https://nav.imydl.tech/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: Nyjwsw # unique identifier
    name: Nyjwsw.com

    url: 'https://www.nyjwsw.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: Nokinsgolfcart # unique identifier
    name: Nokinsgolfcart.com

    url: 'https://nokinsgolfcart.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: love-forex # unique identifier
    name: love-forex.com

    url: 'https://www.love-forex.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: swisschooser # unique identifier
    name: swisschooser.com

    url: 'https://swisschooser.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: e-investingguide # unique identifier
    name: e-investingguide.com

    url: 'https://www.e-investingguide.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: Gxtesjy.com # unique identifier
    name: 寿菌园官网

    url: 'https://www.gxtesjy.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: Kvxr # unique identifier
    name: kvxr.com

    url: 'https://www.kvxr.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: 499h # unique identifier
    name: 499h.com

    url: 'https://499h.com' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
